config/routes.rb
Rails.application.routes.draw do
  get 'profiles/edit'
  get 'profiles/update'
  get '/offers', to: 'offers#index'
  get '/sales', to: 'sneakers#sales', as: 'sales'

  devise_for :users
  root to: "sneakers#index"
  get '/sneakers/magazine', to: 'sneakers#magazine', as: :sneaker_magazine
  resources :sneakers, only: [:index, :show, :new, :create, :edit] do
    resources :offers, only: [:new, :create]
  end

  resources :sneakers, only: [:show, :index, :edit, :update] do
    member do
      post :add_to_cart
    end
  end

  resources :cart_items, only: [:create, :destroy]
  get 'cart', to: 'carts#show', as: :cart
  resources :categories
  get '/brands/:brand_name', to: 'sneakers#brand', as: :brand_sneakers

  # Use the custom sign out route you defined
  delete '/users/sign_out', to: 'sessions#destroy', as: :sign_out_user

  # ... Other routes ...
  resource :profile, only: [:edit, :update]
end

app/views/shared/_add_to_cart.js.erb
var cartCount = <%= current_user.cart.cart_items.sum(:quantity) %>;
$('#cart-count').text(cartCount);

// app/assets/javascripts/cart.js
document.addEventListener('DOMContentLoaded', function() {
  // Update cart count using JavaScript
  var cartCountElement = document.getElementById('cart-count');
  var cartCount = <%= current_user.cart.cart_items.sum(:quantity) %>;
  cartCountElement.textContent = cartCount;
});

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
<div class="help-center">
  <h2>Help Center</h2>
  <a href="">Contact Us</a>
  <a href="">How to order</a>
  <a href="">Return Item</a>
  <a href="">Returns & Exchanges</a>
  <a href="">FAQs</a>
</div>

<div class="help-center">
  <h2>Policies</h2>
  <a href="">Privacy</a>
  <a href="">Security</a>
  <a href="">Site Security</a>
  <a href="">Terms & Conditions</a>

</div>

<div class="help-center">
    <h2>Social Media</h2>
    <a href="#"><i class="fab fa-instagram"></i>Instagram</a>
    <a href="#"><i class="fab fa-facebook"></i>facebook</a>
    <a href="#"><i class="fab fa-twitter"></i>Twitter</a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by Tanya
  </div>
</div>

app/views/shared/_navbar.html.erb
      <% if user_signed_in? %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dw1yozuyk/image/upload/v1691699393/download_10_odqjl7.jpg" %>
    <% end %>

 <button class="navbar-toggler" id="navbarToggler">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse" id="navbarSupportedContent">
       <ul class="navbar-nav ">
        <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
        </li>

          <li class="nav-item">
            <%= link_to "Footwear", categories_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sell", new_sneaker_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sales', sales_path,  class: "nav-link" %>
          </li>

          <li class="nav-item">
           <%= link_to "Magazine", sneaker_magazine_path, class: "nav-link" %>
          </li>

           <% if user_signed_in? %>
         <li class="cart-counter nav-item">
         <%= link_to cart_path do %>
           <%= current_user.cart.cart_items.sum :quantity rescue 0 %>
          <% end %>
         </li>
         <% end %>

           <li class="nav-item dropdown">
     <% if current_user.profile %>
     <%= cl_image_tag 'your_public_id', class: 'avatar dropdown-toggle', id: 'navbarDropdown', data: { bs_toggle: 'dropdown' }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
      <%= image_tag 'https://res.cloudinary.com/dw1yozuyk/image/upload/v1692281101/WhatsApp_Image_2023-08-17_at_16.04.35_jkx4lp.jpg', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>
     <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
      <%# <%= link_to "Action", "#", class: "dropdown-item" %>
      <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
      <!-- Add more dropdown items as needed -->
    </div>
</li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>