config/routes.rb
Rails.application.routes.draw do
  get 'profiles/edit'
  get 'profiles/update'
  get '/offers', to: 'offers#index'
  get '/sales', to: 'sneakers#sales', as: 'sales'

  devise_for :users
  root to: "sneakers#index"
  get '/sneakers/magazine', to: 'sneakers#magazine', as: :sneaker_magazine
  resources :sneakers, only: [:index, :show, :new, :create, :edit] do
    resources :offers, only: [:new, :create]
  end

  resources :sneakers, only: [:show, :index, :edit, :update] do
    member do
      post :add_to_cart
    end
  end

  resources :cart_items, only: [:create, :destroy]
  get 'cart', to: 'carts#show', as: :cart
  resources :categories
  get '/brands/:brand_name', to: 'sneakers#brand', as: :brand_sneakers

  # Use the custom sign out route you defined
  delete '/users/sign_out', to: 'sessions#destroy', as: :sign_out_user

  # ... Other routes ...
  resource :profile, only: [:edit, :update]
end

app/models/sneaker.rb
class Sneaker < ApplicationRecord
  belongs_to :user
  has_many :offers, dependent: :destroy
  has_one_attached :photo
  has_many :cart_items
  belongs_to :category


  enum status: { available: 0, sold: 1 }
  attribute :title, :string
  attribute :model, :string
  attribute :description, :text
  attribute :price, :integer
  
end

app/controllers/sneakers_controller.rb
class SneakersController < ApplicationController
  def index
    @sneakers = Sneaker.left_outer_joins(:offers).where(offers: { id: nil })
    @sneakers = Sneaker.all
    @sneakers = Sneaker.includes(:category) # Make sure you include the associated category
    @sneakers_by_brand = Sneaker.all.group_by(&:brand)

  end

  def show
    @sneaker = Sneaker.find(params[:id])
    @offer = Offer.new
  end

  def edit
    @sneaker = Sneaker.find(params[:id])
  end

  def create
    @sneaker = Sneaker.new(sneaker_params)
    @sneaker.user = current_user
    if @sneaker.save
      redirect_to sneaker_path(@sneaker)
    else
      render "new"
    end
  end

  def new
    @sneaker = Sneaker.new
  end

  def update
    @sneaker = Sneaker.find(params[:id])

    if @sneaker.update(sneaker_params)
      redirect_to @sneaker, notice: 'Sneaker was successfully updated.'
    else
      Rails.logger.info("Update failed with errors: #{sneaker_params.inspect}")
      render :edit
    end
  end


  def add_to_cart
    @sneaker = Sneaker.find(params[:id])
    @cart = current_user.get_cart
    @cart_item = @cart.cart_items.find_or_initialize_by(sneaker: @sneaker)
    @cart_item.increment(:quantity)
    @cart_item.save

    respond_to do |format|
      format.html { redirect_to @sneaker, notice: 'Sneaker added to cart.' }
      format.js   # This will render add_to_cart.js.erb
    end
  end

  def set_cart
    @cart = current_user.cart || current_user.create_cart
  end

  def brand
    brand_name = params[:brand_name]
    @sneakers = Sneaker.where(brand: brand_name)
  end

  def magazine

  end

  def destroy
    @sneaker = Sneaker.find(params[:id])
    @sneaker.destroy
    redirect_to sneakers_path, notice: 'Sneaker was successfully deleted.'
  end

  def sales
    @sneakers_on_sale = Sneaker.where('price < ?', 2500)
  end


  private

  def my_sneakers
    @owned_sneakers_pending = current_user.sneakers.includes(:offers).where(offers: { id: nil })
    @accepted_sneakers = Sneaker.joins(:offers).where(offers: { status: 'accepted', user_id: current_user.id })
    @owned_sneakers_accepted = current_user.sneakers.joins(:offers).where(offers: { status: 'accepted' })
  end

  def sneaker_params
    params.require(:sneaker).permit(:title, :brand, :model, :description, :size, :price, :photo)
  end
end

app/views/sneakers/brand.html.erb
<h1><%= params[:brand_name] %> Sneakers</h1>

<div class="card-container">
  <% @sneakers.each do |sneaker| %>
    <%= link_to sneaker_path(sneaker), class: 'show-details-link' do %>
      <div class="card">
           <%= cl_image_tag sneaker.photo.key %>
        <div class="card-infos">
          <div>
            <p><%= sneaker.model %></p>
          </div>
          <h2 class="card-price">R<%= sneaker.price %></h2>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/sneakers/edit.html.erb
<% Sneaker.all.each do |sneaker| %>
  <% if current_user == sneaker.user %>
    <p><%= sneaker.model %></p>
  <%= link_to 'Delete', sneaker_path(sneaker), method: :delete, data: { confirm: 'Are you sure you want to delete this sneaker?' } %>
  <% end %>
<% end %>


  <%= simple_form_for(@sneaker, html: { class: 'card p-4' }) do |f| %>
    <%= f.input :title, input_html: { class: 'form-control', placeholder: 'Eg: "Rare Air Jordan 1 in Mint Condition!"' } %>
    <%= f.input :brand, collection: ['Nike', 'Adidas', 'Puma', 'Reebok', 'New Balance', 'Converse', 'Vans', 'Fila', 'Balenciaga' ], prompt: "Select a brand" %>
    <%= f.input :model, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
    <%= f.input :size, collection: (3..14).step(0.5).to_a, prompt: "Select a size (UK)" %>
    <%= f.input :price, input_html: { class: 'form-control', placeholder: '£', pattern: "[0-9]*" } %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Update Sneaker' %>
  <% end %>
  <%= link_to 'Back to Sneakers', sneakers_path %>

</div>

app/views/sneakers/index.html.erb
<div class="container">
    <div class="top-three-images">
    <img src="https://res.cloudinary.com/dw1yozuyk/image/upload/v1691692756/basketball_court_wuv3ma.jpg" alt="image">
    <img src="https://res.cloudinary.com/dw1yozuyk/image/upload/v1691696961/244516f83307d916011e0556739c72b1_gievjn.jpg" alt="image">
    <img src="https://res.cloudinary.com/dw1yozuyk/image/upload/v1691696672/OAMC_and_adidas_Introduce_New_Type_O-9_Sneaker_wnvnc6.png" alt="">

   </div>
  <div class="recent">
    <h1>Just Dropped</h1>
  </div>
  <!-- app/views/sneakers/index.html.erb -->
<div class="card-container">
  <% @sneakers.each do |sneaker| %>
    <%= link_to sneaker_path(sneaker), class: 'show-details-link' do %>
      <div class="card">
           <%= cl_image_tag sneaker.photo.key %>
        <div class="card-infos">
          <div>
            <h2><%= sneaker.title %></h2>
            <h2><%= sneaker.brand %></h2>
            <p><%= sneaker.model %></p>
          </div>
          <h2 class="card-price">R<%= sneaker.price %></h2>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<%# <div class="card-container">
  <div class="card-container">
  <% @sneakers_by_brand.each do |brand, sneakers| %>
      <%# <%= link_to(categories_path, class: "first-card") do %>
    <%# <% if brand == "Adidas" %>
      <%# <h2><%= brand %>
        <%# <div class="card"> %>
          <%# <!-- Content of the card --> %>
        <%# </div> %>
      <%# <% end %>
    <%# <% end %>
  <%# <% end %>
<%# </div> %>


      <br>
      <br>
      <hr>
</div>

app/views/sneakers/magazine.html.erb
<!-- app/views/sneakers/magazine.html.erb -->
<div class="magazine-header">
  <div class="magazine-info">
      <h1>Nike</h1>
      <h2>Journal</h2>
      <img src="https://res.cloudinary.com/dw1yozuyk/image/upload/v1692302192/grid_landscape-removebg-preview_1_juuis9.png" alt="">
      <p style="postion:absolute">Stories that move you. </p>
   </div>
</div>


<div class="nike-section">
   <h1>New.</h1>
    <div class="nike-image"style="display:inline-flex;padding: 20px;margin: 0px;width: fit-content;">
      <img src="https://res.cloudinary.com/dw1yozuyk/image/upload/v1692281101/WhatsApp_Image_2023-08-17_at_16.04.35_jkx4lp.jpg" alt="">
    <p>The latest arrival from Drake's ongoing Nike collaboration is a spin on the classic Tech Fleece.
     <br> The Nocta Tech Fleece appears to have a more cozy cut, featuring a relaxed leg compared to the narrow jogger style of a typical Tech Fleece.⁠</p>
    </div>
</div>

<div class="three">
 <img src="https://res.cloudinary.com/dw1yozuyk/image/upload/v1692283811/WhatsApp_Image_2023-08-17_at_16.49.41_y08qxd.jpg" alt="">
 <img src="https://res.cloudinary.com/dw1yozuyk/image/upload/v1692283949/WhatsApp_Image_2023-08-17_at_16.34.47_sletiu.jpg" alt="">
 <div class="info">
  <h2>JUST DO IT</h2>
 </div>
</div>

app/views/sneakers/new.html.erb
<div class="form-div">
  <h1 class="offers-title">SELL KICKS</h1>
  <%= simple_form_for(@sneaker, html: { class: 'card p-4' }) do |f| %>
    <%= f.input :title, input_html: { class: 'form-control', placeholder: 'Eg: "Rare Air Jordan 1 in Mint Condition!"' } %>
    <%= f.input :brand, collection: ['Nike', 'Adidas', 'Puma', 'Reebok', 'New Balance', 'Converse', 'Vans', 'Fila', 'Balenciaga' ], prompt: "Select a brand" %>
    <%= f.input :model, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
    <%= f.input :size, collection: (3..14).step(0.5).to_a, prompt: "Select a size (UK)" %>
    <%= f.input :price, input_html: { class: 'form-control', placeholder: '£', pattern: "[0-9]*" } %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Create Listing', class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/sneakers/sales.html.erb
<!-- app/views/sneakers/sales.html.erb -->

<h1>Sneakers on Sale</h1>

<div class="card-container">
  <% @sneakers_on_sale.each do |sneaker| %>
    <%= link_to sneaker_path(sneaker), class: 'show-details-link' do %>
      <div class="card">
           <%= cl_image_tag sneaker.photo.key %>
        <div class="card-infos">
          <div>
            <h2><%= sneaker.title %></h2>
            <h2><%= sneaker.brand %></h2>
            <p><%= sneaker.model %></p>
          </div>
          <h2 class="card-price">R<%= sneaker.price %></h2>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/sneakers/show.html.erb
  <h1 style="text-align:center; padding:30px;"><%= @sneaker.model %></h1>
<div class="show-card">
  <%= cl_image_tag @sneaker.photo.key, class:'show-card-img'%>
  <div class="card-info">
    <h3>R<%= @sneaker.price %></h3>
    <p>UK Size  <%= @sneaker.size %></p>
    <% if @sneaker.status = 0 %>
      <%= "Available" %>
      <% else %>
      <%= "taken" %>
    <% end %>
   <div class="button-card">
    <%= button_to "Add to Cart", add_to_cart_sneaker_path(@sneaker), method: :post, remote: true , class:"add-to-cart-btn"%>
    <% if current_user.cart && current_user.cart.cart_items.exists?(sneaker: @sneaker) %>
      <%= button_to "Remove", cart_item_path(current_user.cart.cart_items.find_by(sneaker: @sneaker)), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>

   </div>
  </div>
   </div>
  </div>
</div>
<!-- app/views/sneakers/show.html.erb -->
<!-- app/views/carts/show.html.erb -->



<!-- app/views/layouts/application.html.erb -->
  <!-- Other navigation elements -->