config/routes.rb
Rails.application.routes.draw do
  get 'profiles/edit'
  get 'profiles/update'
  get '/offers', to: 'offers#index'
  get '/sales', to: 'sneakers#sales', as: 'sales'

  devise_for :users
  root to: "sneakers#index"
  get '/sneakers/magazine', to: 'sneakers#magazine', as: :sneaker_magazine
  resources :sneakers, only: [:index, :show, :new, :create, :edit] do
    resources :offers, only: [:new, :create]
  end

  resources :sneakers, only: [:show, :index, :edit, :update] do
    member do
      post :add_to_cart
    end
  end

  resources :cart_items, only: [:create, :destroy]
  get 'cart', to: 'carts#show', as: :cart
  resources :categories
  get '/brands/:brand_name', to: 'sneakers#brand', as: :brand_sneakers

  # Use the custom sign out route you defined
  delete '/users/sign_out', to: 'sessions#destroy', as: :sign_out_user

  # ... Other routes ...
  resource :profile, only: [:edit, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuthentication</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.fontshare.com/v2/css?f[]=supreme@2,400,1&f[]=satoshi@900,700,500,701,300,400&f[]=zina@400&display=swap" rel="stylesheet">
<link href="https://api.fontshare.com/v2/css?f[]=supreme@2,400,1&f[]=satoshi@900,700,500,701,300,400&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_include_tag "application", defer: true %>
  </head>
  <body>
<% unless current_page?(new_user_session_path) || current_page?(new_user_registration_path) %>
 <%= render 'shared/navbar' %>
  <% end %>
  <%= render "shared/flashes" %>
    <%= yield %>
  <% if current_page?(root_path) || current_page?(sneakers_path)%>
    <%= render 'shared/footer' %>
   <% end %>
  </body>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const navbarCollapse = document.querySelector("#navbarSupportedContent");
    const navbarToggler = document.querySelector("#navbarToggler");

    navbarToggler.addEventListener("click", function () {
      if (navbarCollapse.style.display === "none" || navbarCollapse.style.display === "") {
        navbarCollapse.style.display = "flex";
      } else {
        navbarCollapse.style.display = "none";
      }
    });
  });
</script>
</html>
<h2>REAL CHANGE<h2>